Apply 'ColorizeVolume' to every frame of a sequence
PerkLab/SlicerSandbox pull request #27
Opened 2024-03-19 09:05 UTC by henrykrumb

Addresses issue https://github.com/PerkLab/SlicerSandbox/issues/26 .

If the selected input volume and segmentation belong to a sequence, a colorized volume is created for each frame of that sequence. The user is prompted beforehand if they really want every item of the sequence to be processed.

2024-03-20 21:14 UTC, lassoan commented
Thanks a lot, this will be a very useful feature! I had trouble reviewing the actual changes because they are masked by all the formatting changes. Would you be able to move formatting changes into a separate commit? (e.g., use the code formatter on the original source code, commit; then add all the changes in a second commit => then in te second commit we should only have the functional changes). Thank you!

2024-04-01 17:20 UTC, lassoan requested changes
Thanks a lot for your contribution. I really appreciate that you developed and shared this new feature - it looks great!

It is also nice that you are improving the style of the code (using " consistently, fixing usage of spaces, etc.). However, the amount of style changes are so excessive and the breaking up of quite short lines into several lines was so annoying and made the code harder to read, that I just could not force myself to complete the meaningful part of the review.

Could you please move all style changes into a separate commit and change your autoformatter settings to not to break up lines that are shorter than 160 characters?

If you feel that you have already done enough by contributing this work and would rather not spend any time on this then let me know, I completely understand. Then I'll try to find the time and patience to deal with this as is.

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +                "This module requires a more recent version of Slicer. Please download and install latest Slicer Preview Release."
There is no need for breaking this single line command into 3 lines. It is maybe 10-15 characters narrower, but 3x longer.

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            slicer.mrmlScene, slicer.mrmlScene.StartCloseEvent, self.onSceneStartClose
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            slicer.mrmlScene, slicer.mrmlScene.EndCloseEvent, self.onSceneEndClose
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            "currentNodeChanged(vtkMRMLNode*)", self.onOutputRgbaVolumeSelected
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            "clicked(bool)", self.onResetVolumeRenderingSettingsButton
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            "clicked(bool)", self.onVolumeRenderingSettingsButton
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            "clicked(bool)", self.onResetToDefaultsButton
no need for breaking into 3 lines

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +            "valueChanged(double)", self.onUpdateVolumeRenderingTransferFunction
OK, I stop commenting on this, just revert all these breakups of single-line commands into 3 lines. It just does not make any sense.

2024-04-01 17:20 UTC, lassoan commented on ColorizeVolume/ColorizeVolume.py
> +                )  # extra values: midpoint, sharpness
comment misplaced (it refers to values 0.5, 0.0)

2024-04-02 08:38 UTC, henrykrumb commented
Hi Andras,

I am really sorry for the inconvenience. It is a habit of mine to use black as an auto-formatter on every Python file I edit, and I didn't notice before committing.

I will revert the changes made by the auto-formatter (many of which don't even make much sense, as you pointed out) and create another commit with the changes I consider final.

2024-04-02 08:55 UTC, henrykrumb commented
I just reverted the changes made by the auto-formatter and kept the imports local to functions (thank you for the hint, I will consider it in the future!).

I also tested this commit with a version of vanilla Slicer with my modified version of TotalSegmentator (https://github.com/lassoan/SlicerTotalSegmentator/pull/56) and the example CTA sequence and it still works, so I guess it didn't break anything.

Again, I'm sorry for the inconvenience and I hope you didn't take too much time to review the formatting.

2024-04-03 03:20 UTC, lassoan approved these changes
I've made a few simplifications (use Sequences module logic to get sequence browser, moved confirmation popup to module GUI, etc.). It all looks good now. Thanks again for your contribution!

2024-04-03 03:20 UTC, merged